name: model_factory_example
description: A starting point for Dart libraries or applications.
version: 1.0.2
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <4.0.0"

dependency_overrides:
  model_factory:
    path: ../

dev_dependencies:
  build_runner: ^2.4.6
  model_factory_generator:
    path: ../model_factory_generator/
