name: model_factory
description: A starting point for Dart libraries or applications.
version: 1.1.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  build: ^2.0.3
  path: ^1.8.0
  source_gen: ^1.0.3
  dart_style: ^2.0.2
  glob: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
