name: model_factory
description: A starting point for Dart libraries or applications.
version: 1.3.5
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
