name: model_factory
description: Generate model boiler plate
version: 4.6.1
repository: https://github.com/ekasetiawans/model_factory

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  get_it: ^8.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.6
  melos: ^6.2.0
