targets:
  $default:
    builders:
      model_factory_generator|builder:
        enabled: true

      model_factory_generator|resolver:
        enabled: true

      model_factory_generator|generator:
        enabled: true

builders:
  builder:
    import: "package:model_factory_generator/model_factory_generator.dart"
    builder_factories: ["codeGeneratorBuilder"]
    build_extensions: {".dart": ["model_factory_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    runs_before: ["resolver", "generator"]
    applies_builders: ["source_gen|combining_builder"]

  resolver:
    import: "package:model_factory_generator/model_factory_generator.dart"
    builder_factories: ["codeGeneratorResolver"]
    build_extensions: { ".dart": [".model_factory.info"] }
    auto_apply: dependents
    build_to: cache
    runs_before: ["generator"]

  generator:
    import: "package:model_factory_generator/model_factory_generator.dart"
    builder_factories: ["codeGeneratorFactory"]
    build_extensions:
      "$lib$": ["models_factories.dart"]
      "$test": ["models_factories.dart"]
    required_inputs: [".model_factory.info"]
    auto_apply: dependents
    build_to: source
