targets:
  $default:
    builders:
      model_factory_generator|builder:
        enabled: true

      model_factory_generator|resolver:
        enabled: true

      model_factory_generator|generator:
        enabled: true

builders:
  builder:
    import: "package:model_factory_generator/builder.dart"
    builder_factories: ["codeGeneratorBuilder"]
    build_extensions:
      ".dart": [".model.dart"]
    auto_apply: dependents
    build_to: source

  resolver:
    import: "package:model_factory_generator/builder.dart"
    builder_factories: ["codeGeneratorResolver"]
    build_extensions: { ".dart": [".model_factory.info"] }
    auto_apply: dependents
    build_to: cache

  generator:
    import: "package:model_factory_generator/builder.dart"
    builder_factories: ["codeGeneratorFactory"]
    build_extensions:
      "$lib$": ["models_factories.dart"]
      "$test": ["models_factories.dart"]
    required_inputs: [".model_factory.info"]
    auto_apply: dependents
    build_to: source
