name: model_factory_generator
description: Model generator based on model_factory.
version: 1.1.6
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  model_factory: ">=1.3.8 <1.4.0"
  meta: ">=1.3.0 <2.0.0"

  analyzer: ">=1.0.0 <4.0.0"
  build: ">=2.0.0 <3.0.0"

  yaml: ">=3.1.0 <4.0.0"
  path: ">=1.8.0 <2.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  glob: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.17.10
