name: model_factory_generator
description: Model generator based on model_factory.
version: 2.4.0
repository: https://github.com/ekasetiawans/model_factory/tree/master/model_factory_generator

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  model_factory: ^2.4.0
  meta: ">=1.3.0 <2.0.0"

  analyzer: ">=1.0.0 <7.0.0"
  build: ">=2.0.0 <3.0.0"

  yaml: ">=3.1.0 <4.0.0"
  path: ">=1.8.0 <2.0.0"
  source_gen: ">=1.0.0 <2.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  glob: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^2.0.2
  test: ^1.24.6
