// ignore_for_file: type=lint

// This file is autogenerated by model_factory
// DO NOT MODIFY BY HAND
// To re-generate this file, run:
//    flutter pub run build_runner build

import 'package:model_factory/model_factory.dart';
import 'package:model_factory_example/models/model_custom.dart' as m0;
import 'package:model_factory_example/models/my_model.dart' as m1;
import 'package:model_factory_example/models/t_model.dart' as m2;

class JsonRegistrant {
  static void register() {
    registerDefaultAdapters();
    GetIt.I.registerSingleton<JsonAdapter<m0.ModelWithCustom?>>(
        m0.ModelWithCustomJsonAdapter());
    GetIt.I.registerSingleton<JsonAdapter<List<m0.ModelWithCustom>?>>(
        ListJsonAdapter<m0.ModelWithCustom>());
    GetIt.I
        .registerSingleton<JsonAdapter<m1.MyModel?>>(m1.MyModelJsonAdapter());
    GetIt.I.registerSingleton<JsonAdapter<List<m1.MyModel>?>>(
        ListJsonAdapter<m1.MyModel>());
    GetIt.I.registerSingleton<JsonAdapter<m2.Parent?>>(m2.ParentJsonAdapter());
    GetIt.I.registerSingleton<JsonAdapter<List<m2.Parent>?>>(
        ListJsonAdapter<m2.Parent>());
    GetIt.I.registerSingleton<JsonAdapter<m2.Kid?>>(m2.KidJsonAdapter());
    GetIt.I.registerSingleton<JsonAdapter<List<m2.Kid>?>>(
        ListJsonAdapter<m2.Kid>());
  }
}
