// ignore_for_file: type=lint

// This file is autogenerated by model_factory
// DO NOT MODIFY BY HAND
// To re-generate this file, run:
//    flutter pub run build_runner build

import 'package:model_factory/model_factory.dart';
import 'package:model_factory_example/models/model_custom.dart' as m0;
import 'package:model_factory_example/models/my_model.dart' as m1;
import 'package:model_factory_example/models/t_model.dart' as m2;

class JsonRegistrant {
  static void register() {
    registerDefaultAdapters();
    m0.ModelWithCustomJsonAdapter.register();
    m1.MyModelJsonAdapter.register();
    m2.ParentJsonAdapter.register();
    m2.KidJsonAdapter.register();
  }
}
