// ignore_for_file: type=lint

// This file is autogenerated by model_factory
// DO NOT MODIFY BY HAND
// To re-generate this file, run:
//    flutter pub run build_runner build

import 'package:model_factory/model_factory.dart';
import 'package:model_factory_example/models/model_custom.dart' as m0;
import 'package:model_factory_example/models/my_model.dart' as m1;

void registerFactories() {
  registerJsonFactory<m0.ModelWithCustom>(
      (json) => m0.ModelWithCustom.fromJson(json));
  registerJsonFactory<m0.ModelWithCustom?>(
      (json) => json == null ? null : m0.ModelWithCustom.fromJson(json));
  registerJsonFactory<m1.MyModel>((json) => m1.MyModel.fromJson(json));
  registerJsonFactory<m1.MyModel?>(
      (json) => json == null ? null : m1.MyModel.fromJson(json));
}
