// This file is autogenerated by model_factory
// DO NOT MODIFY BY HAND
// To re-generate this file, run:
//    flutter pub run build_runner build

import 'package:model_factory/model_factory.dart';
import 'package:model_factory_example/models/model_lain.dart' as m0;

void registerFactories() {
  registerJsonFactory((json) => m0.ModelA.fromJson(json));
  registerJsonFactory((json) => m0.ModelB.fromJson(json));
}
