// ignore_for_file: type=lint

// This file is autogenerated by model_factory
// DO NOT MODIFY BY HAND
// To re-generate this file, run:
//    flutter pub run build_runner build

import 'package:model_factory/model_factory.dart';
import 'package:model_factory_example/models/model_custom.dart' as m0;

void registerFactories() {
  registerJsonFactory((json) => m0.ModelWithCustom.fromJson(json));
}
